version: '3.8'

services:
  app:
    image: springredis:v1
    depends_on:
      - postgres
      - redis
    ports:
        - "8080:8080"
    networks:
      - postgres


  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped


  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  postgres: